name: "Maya C. Gupta"
markdown: kramdown
# Site settings
title: Maya C. Gupta
description: > 
  This is the personal website of Maya Gupta, the wandering library person / philologist / whatever that is, not Maya Gupta the roboticist or Maya Gupta the friend of animals. Though I do like animals.
baseurl: "" 
url: "http://mayacgupta.com"
sass:
  sass_dir: assets/sass
